language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "export PATH=$PWD/bin:$PATH"
#    - "cpanm --quiet --notest File::Which"

script:
    - "injecta --version"
    - "injecta --help"
    - "injecta --check dummy"
    - "injecta dummy"
    - "injecta |& grep 'Need at least 1'"
    - injecta dummy --myinc --myinc --myinc |& grep "'myinc' => 3"
    - injecta dummy --myint -42 |& grep "myint' => '-42'"
    - "! injecta file1 file2"
